name: "Integration tests"
on:
  push:
    branches:
      - feature/tests

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment and wait for docker to finish building"
        run: docker compose -f ./src/__tests__/setup/docker-compose.yaml up -d --wait
      - name: "End to end tests"
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          wait-on: "http://localhost:8000"
      - name: "Tear down environment"
        run: docker compose -f ./src/__tests__/setup/docker-compose.yaml down